### ISSUE TITLE
vxThresholdNode stride of Output image

### ISSUE THREAD

**Issue by CACUser** [GPUOpen-ProfessionalCompute-Libraries/amdovx-core#11]
Hi - When I use the vxThresholdNode the stride doesn't seem to be set for the output image. I am unable to use this output image as input to another node because of this. The input image to vxThresholdNode is of  VX_DF_IMAGE_U8 type.  Should I be doing something else to ensure that I get an output image with the stride set correctly?

Thanks!
Mayura

**Comment by rgiduthuri** [comment]
Hi, the image specific parameters, such as, stride are set by the framework and nodes in the graph just use the stride during execution.

What API are you using to get the stride? It will be easy to answer if you can share the test case.

**Comment by CACUser** [comment]
thanks for your reply. 

I am including vx_compatibilty.h in order to build my project.
The graph looks like this:

vx_node nodes[] =
		{
		    vxColorConvertNode(    graph, ovImgRGB, ovImgYUV ),
		    vxChannelExtractNode(  graph, ovImgYUV, VX_CHANNEL_Y, ovImgGray),
		    vxWarpPerspectiveNode( graph, ovImgGray, ovH, VX_INTERPOLATION_TYPE_BILINEAR, ovImgMapped),
		    vxConvolveNode(        graph, ovImgMapped, ovFilter, ovImgEdges),
		    vxThresholdNode(       graph, ovImgEdges, ovThreshold, ovImgBin),
		    userNode( graph, ovImgBin, ovLineArray, ..... mor parameters)
		};

In userNode ovImgBin needs to be passed to a OpenCV function and I need to use the cv::Mat function.
I use the following API:
    status = vxGetValidRegionImage(image, &rect);

    vx_imagepatch_addressing_t addr;
 
    status = vxAccessImagePatch(image, &rect, 0, &addr, &ptr, VX_WRITE_ONLY);
   
    vx_df_image imageFormat;
    status = vxQueryImage(image, VX_IMAGE_ATTRIBUTE_FORMAT, &imageFormat, sizeof(imageFormat));
   
    when image format is VX_DF_IMAGE_U8 I am getting
	addr.stride_x = 4328524
	addr.stride_y = 0

   when image format is VX_DF_IMAGE_RGB I am getting (which is fine)
       addr.stride_x = 3
       addr.stride_y = 2880

**Comment by CACUser** [comment]
Hi - do you have any insights into why I am seeing this? Thanks.

**Comment by rgiduthuri** [comment]
Are you setting the ptr to NULL before vxAccessImagePatch?

**Comment by CACUser** [comment]
Yes, the ptr is being set to NULL before vxAccessImagePatch. Here is some more data:

Using vxAccessImagePatch and vxCommitImagePatch with an avi file:

with image format VX_DF_IMAGE_U8 I am getting addr.stride_x = 6547712 and addr.stride_y = 0
with image format VX_DF_IMAGE_RGB I am getting addr.stride_x = 3 and addr.stride_y = 2304

Using vxAccessImagePatch and vxCommitImagePatch with an mp4 file:

with image format VX_DF_IMAGE_U8 I am getting addr.stride_x = 6547712 and addr.stride_y = 0
with image format VX_DF_IMAGE_RGB I am getting addr.stride_x = 3 and addr.stride_y = 2880


Using vxMapImagePatch and vxUnmapImagePatch with an avi file - this is working correctly:

with image format VX_DF_IMAGE_U8 I am getting addr.stride_x = 1 and addr.stride_y = 224
with image format VX_DF_IMAGE_RGB I am getting addr.stride_x = 3 and addr.stride_y = 2304

Using vxMapImagePatch and vxUnmapImagePatch with an mp4 file (seem to be getting the right values - but after this I am getting a segmentation fault):

with image format VX_DF_IMAGE_U8 I am getting addr.stride_x = 1 and addr.stride_y = 224
with image format VX_DF_IMAGE_RGB I am getting addr.stride_x = 3 and addr.stride_y = 2880

**Comment by rgiduthuri** [comment]
I just pushed release 0.9.4 that has a related bug fix. Could you please try? Thx

**Comment by CACUser** [comment]
thanks. Wanted to first mention that the segmentation fault I mentioned above is coming from some  other issue - returning an array from a user kernel.
But I tried to build libopenvx (rel 0.9.4) to resolve the stride issue with vxAccessImagePatch  - I am getting the following error: vx_api.cpp:524:43: error: ‘_stricmp’ was not declared in this scope

**Comment by rgiduthuri** [comment]
Committed a fix to the build error on linux. Please let me know if it works now. Thx

**Comment by CACUser** [comment]
The build works. But the stride issue is still there if I use AccessImagePatch. Everything is fine if I use MapImagePatch.
